name: Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Python Tests
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Start Database
        run: docker-compose up -d db
      - name: Run the Python Tests
        run: |
            # This configures the test stuff
            echo "127.0.0.1 db localhost" | sudo tee -a /etc/hosts
            sudo apt-get update -qy
            sudo apt-get install -y python3-dev python3-pip
            pip install pipenv
            pipenv install --system --deploy
            python3 manage.py migrate
            python3 manage.py test
            coverage run --source='.' manage.py test
            coverage report -m
            coverage-badge

  fossa:
    name: FOSSA
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run FOSSA to check for vulnerabilities
        uses: fossas/fossa-action@v2
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
      - name: Build Docker Image
        run: >
          docker-compose build
      - name: Run FOSSA Container scan to check for vulnerabilities
        uses: fossas/fossa-action@v2
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          container: app


  hawkscan:
    name: StackHawk DAST
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run the Vuln Django Containers
        run: docker-compose up -d
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v1.2.1
        with: 
          apiKey: ${{ secrets.HAWK_API_KEY }}
          configurationFiles: stackhawk.yml stackhawk-github.yml
          network: fossa-stackhawk-demo_default
